/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface BoardIdeasInterface extends utils.Interface {
  functions: {
    "burnAccessPass()": FunctionFragment;
    "commentOnIdea(string,uint64)": FunctionFragment;
    "createIdea(string,string)": FunctionFragment;
    "mintAccessPass()": FunctionFragment;
    "transferAccessPass(address)": FunctionFragment;
    "voteOnIdea(uint8,uint64)": FunctionFragment;
    "ACCESS_PASS()": FunctionFragment;
    "ACCESS_PASS_PRICE()": FunctionFragment;
    "comments(uint64,uint256)": FunctionFragment;
    "hasAccessPass(address)": FunctionFragment;
    "ideaCommentsLength(uint64)": FunctionFragment;
    "ideas(uint64)": FunctionFragment;
    "totalIdeas()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "URI()": FunctionFragment;
    "votes(uint64,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "burnAccessPass"
      | "commentOnIdea"
      | "createIdea"
      | "mintAccessPass"
      | "transferAccessPass"
      | "voteOnIdea"
      | "ACCESS_PASS"
      | "ACCESS_PASS_PRICE"
      | "comments"
      | "hasAccessPass"
      | "ideaCommentsLength"
      | "ideas"
      | "totalIdeas"
      | "totalSupply"
      | "URI"
      | "votes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burnAccessPass",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commentOnIdea",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createIdea",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAccessPass",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAccessPass",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnIdea",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ACCESS_PASS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACCESS_PASS_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "comments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccessPass",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ideaCommentsLength",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ideas", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalIdeas",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "URI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "burnAccessPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commentOnIdea",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createIdea", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintAccessPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAccessPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteOnIdea", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ACCESS_PASS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACCESS_PASS_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "comments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasAccessPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ideaCommentsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ideas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalIdeas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "URI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;

  events: {
    "IdeaCommented(uint64,uint64)": EventFragment;
    "IdeaCreated(uint64)": EventFragment;
    "IdeaVotesUpdated(uint64,uint64,int64)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "IdeaCommented"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IdeaCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IdeaVotesUpdated"): EventFragment;
}

export interface IdeaCommentedEventObject {
  _ideaId: BigNumber;
  _commentIndex: BigNumber;
}
export type IdeaCommentedEvent = TypedEvent<
  [BigNumber, BigNumber],
  IdeaCommentedEventObject
>;

export type IdeaCommentedEventFilter = TypedEventFilter<IdeaCommentedEvent>;

export interface IdeaCreatedEventObject {
  _ideaId: BigNumber;
}
export type IdeaCreatedEvent = TypedEvent<[BigNumber], IdeaCreatedEventObject>;

export type IdeaCreatedEventFilter = TypedEventFilter<IdeaCreatedEvent>;

export interface IdeaVotesUpdatedEventObject {
  _voteId: BigNumber;
  _upvotes: BigNumber;
  _downvotes: BigNumber;
}
export type IdeaVotesUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  IdeaVotesUpdatedEventObject
>;

export type IdeaVotesUpdatedEventFilter =
  TypedEventFilter<IdeaVotesUpdatedEvent>;

export interface BoardIdeas extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BoardIdeasInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burnAccessPass(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commentOnIdea(
      _text: string,
      _ideaId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createIdea(
      _title: string,
      _description: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintAccessPass(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferAccessPass(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voteOnIdea(
      _voteType: BigNumberish,
      _ideaId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ACCESS_PASS(overrides?: CallOverrides): Promise<[number]>;

    ACCESS_PASS_PRICE(overrides?: CallOverrides): Promise<[number]>;

    comments(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        text: string;
        createdBy: string;
        createdAt: BigNumber;
      }
    >;

    hasAccessPass(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    ideaCommentsLength(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    ideas(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, BigNumber, string, string] & {
        id: BigNumber;
        title: string;
        upvotes: BigNumber;
        downvotes: BigNumber;
        createdAt: BigNumber;
        createdBy: string;
        description: string;
      }
    >;

    totalIdeas(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[number]>;

    URI(overrides?: CallOverrides): Promise<[string]>;

    votes(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string, number] & { voter: string; voteType: number }>;
  };

  burnAccessPass(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commentOnIdea(
    _text: string,
    _ideaId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createIdea(
    _title: string,
    _description: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintAccessPass(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferAccessPass(
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voteOnIdea(
    _voteType: BigNumberish,
    _ideaId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ACCESS_PASS(overrides?: CallOverrides): Promise<number>;

  ACCESS_PASS_PRICE(overrides?: CallOverrides): Promise<number>;

  comments(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber] & {
      text: string;
      createdBy: string;
      createdAt: BigNumber;
    }
  >;

  hasAccessPass(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  ideaCommentsLength(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ideas(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, BigNumber, BigNumber, string, string] & {
      id: BigNumber;
      title: string;
      upvotes: BigNumber;
      downvotes: BigNumber;
      createdAt: BigNumber;
      createdBy: string;
      description: string;
    }
  >;

  totalIdeas(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<number>;

  URI(overrides?: CallOverrides): Promise<string>;

  votes(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<[string, number] & { voter: string; voteType: number }>;

  callStatic: {
    burnAccessPass(overrides?: CallOverrides): Promise<void>;

    commentOnIdea(
      _text: string,
      _ideaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createIdea(
      _title: string,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintAccessPass(overrides?: CallOverrides): Promise<void>;

    transferAccessPass(_to: string, overrides?: CallOverrides): Promise<void>;

    voteOnIdea(
      _voteType: BigNumberish,
      _ideaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ACCESS_PASS(overrides?: CallOverrides): Promise<number>;

    ACCESS_PASS_PRICE(overrides?: CallOverrides): Promise<number>;

    comments(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        text: string;
        createdBy: string;
        createdAt: BigNumber;
      }
    >;

    hasAccessPass(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    ideaCommentsLength(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ideas(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, BigNumber, string, string] & {
        id: BigNumber;
        title: string;
        upvotes: BigNumber;
        downvotes: BigNumber;
        createdAt: BigNumber;
        createdBy: string;
        description: string;
      }
    >;

    totalIdeas(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<number>;

    URI(overrides?: CallOverrides): Promise<string>;

    votes(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string, number] & { voter: string; voteType: number }>;
  };

  filters: {
    "IdeaCommented(uint64,uint64)"(
      _ideaId?: null,
      _commentIndex?: null
    ): IdeaCommentedEventFilter;
    IdeaCommented(
      _ideaId?: null,
      _commentIndex?: null
    ): IdeaCommentedEventFilter;

    "IdeaCreated(uint64)"(_ideaId?: null): IdeaCreatedEventFilter;
    IdeaCreated(_ideaId?: null): IdeaCreatedEventFilter;

    "IdeaVotesUpdated(uint64,uint64,int64)"(
      _voteId?: null,
      _upvotes?: null,
      _downvotes?: null
    ): IdeaVotesUpdatedEventFilter;
    IdeaVotesUpdated(
      _voteId?: null,
      _upvotes?: null,
      _downvotes?: null
    ): IdeaVotesUpdatedEventFilter;
  };

  estimateGas: {
    burnAccessPass(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commentOnIdea(
      _text: string,
      _ideaId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createIdea(
      _title: string,
      _description: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintAccessPass(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferAccessPass(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voteOnIdea(
      _voteType: BigNumberish,
      _ideaId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ACCESS_PASS(overrides?: CallOverrides): Promise<BigNumber>;

    ACCESS_PASS_PRICE(overrides?: CallOverrides): Promise<BigNumber>;

    comments(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasAccessPass(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    ideaCommentsLength(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ideas(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    totalIdeas(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    URI(overrides?: CallOverrides): Promise<BigNumber>;

    votes(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnAccessPass(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commentOnIdea(
      _text: string,
      _ideaId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createIdea(
      _title: string,
      _description: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintAccessPass(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferAccessPass(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voteOnIdea(
      _voteType: BigNumberish,
      _ideaId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ACCESS_PASS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ACCESS_PASS_PRICE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    comments(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasAccessPass(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ideaCommentsLength(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ideas(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalIdeas(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    URI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    votes(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
