/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BoardIdeas } from "./BoardIdeas";
export * as factories from "./factories";
export { BoardIdeas__factory } from "./factories/BoardIdeas__factory";
